python extract_proof_steps.py --filter 0
python extract_proof_steps.py --filter 1
python extract_proof_steps.py --filter 2
python extract_proof_steps.py --filter 3
python extract_proof_steps.py --filter 4
python extract_proof_steps.py --filter 5
python extract_proof_steps.py --filter 6
python extract_proof_steps.py --filter 7
python extract_proof_steps.py --filter 8
python extract_proof_steps.py --filter 9
python extract_proof_steps.py --filter a
python extract_proof_steps.py --filter b
python extract_proof_steps.py --filter c
python extract_proof_steps.py --filter d
python extract_proof_steps.py --filter e
python extract_proof_steps.py --filter f
